/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

/**
 *
 * @author Sissoko && Elay
 * @date 4 mai 2013 14:02:32
 */
public enum RightEnum {

    ACCESS_ADMIN,
    ADD_ROLE_TO_USER,
    ADD_RIGHT_TO_ROLE,
    ADD_USER_TO_DENDRITE,
    ADD_USER_TO_MY_DENDRITE,
    ADD_AND_REMOVE_ROLE_USER,
    ADD_AND_REMOVE_RIGHT_ROLE,
    ADD_AND_REMOVE_USER_TO_DENDRITE,
    ADD_AND_REMOVE_POSTE_TO_DENDRITE,
    ADD_AND_REMOVE_ROLE_TO_POSTE,
    ADD_AND_REMOVE_POSTE_TO_USER,
    CREATE_USER,
    CREATE_EVENT,
    CREATE_DENDRITE,
    CREATE_RIGHT,
    CREATE_ELECTION,
    CREATE_MY_ELECTION,
    CREATE_MY_EVENT,
    CREATE_CANDIDATURE,
    CREATE_MY_CANDIDATURE,
    DELETE_USER,
    DELETE_ARTICLE,
    DELETE_EVENT,
    DELETE_MY_EVENT,
    DELETE_ANNOUNCE,
    DELETE_MY_ANNOUNCE,
    DELETE_DENDRITE,
    DELETE_ROLE,
    DELETE_ELECTION,
    DELETE_CANDIDATURE,
    DELETE_MY_ELECTION,
    DELETE_POSTE,
    DELETE_FEEDBACK,
    DELETE_MY_FEEDBACK,
    EDIT_FEEDBACK,
    EDIT_MY_FEEDBACK,
    EDIT_EVENT,
    EDIT_MY_EVENT,
    EDIT_MY_ANNOUNCE,
    EDIT_DENDRITE,
    EDIT_MY_DENDRITE,
    EDIT_ROLE,
    EDIT_USER,
    EDIT_MY_USER,
    EDIT_ELECTION,
    EDIT_CANDIDATURE,
    EDIT_MY_ELECTION,
    EDIT_ARTICLE,
    EDIT_POSTE,
    EDIT_MY_POSTE, 
    EDIT_MY_CANDIDATURE, 
    EDIT_ANNOUNCE,
    ENABLE_DESABLE_USER,
    REMOVE_RIGHT_FROM_ROLE,
    REMOVE_USER_FROM_DENDRITE,
    REMOVE_USER_FROM_MY_DENDRITE,
    REMOVE_ROLE_FROM_USER, 
    SEND_MESSAGE, 
    SEND_MY_MESSAGE;
}
